from enum import StrEnum


class EnvironmentType(StrEnum):
    CLASSROOM = "CLASSROOM"
    LABORATORY = "LABORATORY"
    AUDITORIUM = "AUDITORIUM"
    MEETING_ROOM = "MEETING_ROOM"
    STUDIO = "STUDIO"
    MULTIPURPOSE = "MULTIPURPOSE"


class EnvironmentCriticality(StrEnum):
    COMMON = "COMMON"
    CONTROLLED = "CONTROLLED"
    RESTRICTED = "RESTRICTED"


class ResourceType(StrEnum):
    EQUIPMENT = "EQUIPMENT"
    FURNITURE = "FURNITURE"
    SOFTWARE_LICENSE = "SOFTWARE_LICENSE"
    KEY = "KEY"
    SUPPLY = "SUPPLY"
    KIT = "KIT"


class ResourceCategory(StrEnum):
    IT = "IT"
    AUDIOVISUAL = "AUDIOVISUAL"
    LABORATORY = "LABORATORY"
    GENERAL = "GENERAL"
    FURNITURE = "FURNITURE"
    COMPUTING = "COMPUTING"
    ACCESS = "ACCESS"


class ResourceCheckoutStatus(StrEnum):
    CHECKED_OUT = "CHECKED_OUT"
    RETURNED = "RETURNED"
    OVERDUE = "OVERDUE"
    LOST = "LOST"


class ReservationPurpose(StrEnum):
    CLASS = "CLASS"
    MEETING = "MEETING"
    RESEARCH = "RESEARCH"
    EVENT = "EVENT"
    MAINTENANCE = "MAINTENANCE"
    TRAINING = "TRAINING"


class ReservationStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    PRE_BLOCKED = "PRE_BLOCKED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    IN_USE = "IN_USE"
    COMPLETED = "COMPLETED"
    NO_SHOW = "NO_SHOW"
    EXPIRED = "EXPIRED"


class ReservationType(StrEnum):
    SIMPLE = "SIMPLE"
    RECURRING = "RECURRING"
    COMPOSITE_PARENT = "COMPOSITE_PARENT"
    COMPOSITE_CHILD = "COMPOSITE_CHILD"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REQUIRES_CHANGES = "REQUIRES_CHANGES"
    ESCALATED = "ESCALATED"


class CalendarBlockType(StrEnum):
    ADMIN_BLOCK = "ADMIN_BLOCK"
    MAINTENANCE = "MAINTENANCE"
    RECURRING_EVENT = "RECURRING_EVENT"
    BUFFER = "BUFFER"
    HOLIDAY = "HOLIDAY"
    CLOSURE = "CLOSURE"


class PenaltyType(StrEnum):
    NO_SHOW = "NO_SHOW"
    LATE_CANCELLATION = "LATE_CANCELLATION"
    DAMAGE = "DAMAGE"
    MISUSE = "MISUSE"
    OVERTIME = "OVERTIME"
    SAFETY_VIOLATION = "SAFETY_VIOLATION"


class PenaltyStatus(StrEnum):
    PENDING = "PENDING"
    APPLIED = "APPLIED"
    WAIVED = "WAIVED"
    UNDER_APPEAL = "UNDER_APPEAL"
    RESOLVED = "RESOLVED"


class AppealStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AuditAction(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    CANCEL = "CANCEL"
    CHECKIN = "CHECKIN"
    CHECKOUT = "CHECKOUT"
    ASSIGN_RESOURCE = "ASSIGN_RESOURCE"
    REMOVE_RESOURCE = "REMOVE_RESOURCE"


class BufferType(StrEnum):
    PRE = "PRE"
    POST = "POST"


class SupportType(StrEnum):
    IT_SUPPORT = "IT_SUPPORT"
    AUDIOVISUAL = "AUDIOVISUAL"
    LAB_TECHNICIAN = "LAB_TECHNICIAN"
    SECURITY = "SECURITY"
    CLEANING = "CLEANING"


class RecommendationStrategy(StrEnum):
    FIRST_FIT = "FIRST_FIT"
    WEIGHTED_SCORE = "WEIGHTED_SCORE"


class CheckinMethod(StrEnum):
    MANUAL = "MANUAL"
    QR_CODE = "QR_CODE"
    CARD_ACCESS = "CARD_ACCESS"
    KEY_PICKUP = "KEY_PICKUP"
    SENSOR_TRIGGERED = "SENSOR_TRIGGERED"


class IncidentSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    TECHNICIAN = "TECHNICIAN"
    REQUESTER = "REQUESTER"


class AttachmentType(StrEnum):
    STUDENT = "STUDENT"
    PROFESSOR = "PROFESSOR"
    STAFF = "STAFF"
    EXTERNAL = "EXTERNAL"


class ResourceAttachment(StrEnum):
    FIXED = "FIXED"
    MOBILE = "MOBILE"


class NotificationType(StrEnum):
    RESERVATION_APPROVED = "RESERVATION_APPROVED"
    RESERVATION_REJECTED = "RESERVATION_REJECTED"
    SUPPORT_PENDING = "SUPPORT_PENDING"
    PENALTY_APPLIED = "PENALTY_APPLIED"
    APPEAL_RESOLVED = "APPEAL_RESOLVED"
    COMPOSITE_REVISION_REQUIRED = "COMPOSITE_REVISION_REQUIRED"
